# Generated by Django 6.1.1 on 2026-09-06 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('P', 'planning'), ('IN', 'in_progress'), ('C', 'completed'), ('A', 'archived')], default='P', max_length=2),
        ),
    ]
