# Generated by Django 6.1.1 on 2026-09-09 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('FE', 'Feature'), ('BU', 'Bug'), ('FX', 'Fix'), ('IM', 'Improvement'), ('LE', 'Learning'), ('AR', 'Architecture'), ('EX', 'Experiment'), ('MI', 'Milestone'), ('NO', 'Note')], default='NO', max_length=2)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.RemoveIndex(
            model_name='documentation',
            name='projects_do_created_43d567_idx',
        ),
        migrations.AddField(
            model_name='project',
            name='default_image',
            field=models.CharField(choices=[('pro-default-1', 'Default 1'), ('pro-default-2', 'Default 2'), ('pro-default-3', 'Default 3')], default='pro-default-1', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('PL', 'planning'), ('IN', 'in_progress'), ('CO', 'completed'), ('AR', 'archived')], default='PL', max_length=2),
        ),
        migrations.AddField(
            model_name='buildupdate',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='projects.project'),
        ),
        migrations.RemoveField(
            model_name='documentation',
            name='project',
        ),
        migrations.AddIndex(
            model_name='buildupdate',
            index=models.Index(fields=['-created'], name='projects_bu_created_fe0347_idx'),
        ),
        migrations.DeleteModel(
            name='Documentation',
        ),
    ]
