# Generated by Django 6.1.1 on 2026-09-27 21:33

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_drop_thumb_column'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
