# Generated by Django 6.1.1 on 2026-09-27 23:47

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_tags'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='separate tags with commas', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
